### PR TITLE
EffectFn Refactor; Tilemap Example

### PR DESCRIPTION
**Pull request by hugh-fox**
Apologies, this one is a bit of a mess.
About half of the changes are replacing Fn with EffectFn as well as formatting with purty, while the other half is making a new example and getting it working.
Additionally, as part of the JS refactor I tried using ES6 fat arrows but ran into some strange "expression expected: => " errors, but those might just be me not knowing Javascript.
The readme example is more verbose now, perhaps I should keep it short?

### CODE REVIEW

**Comment by lfarroco** [comment]
thanks for the contribution, @Rekihyt ! I will take a couple of days to review that
I think that the purescript compiler is not able to properly parse ES6 (looking at popular packages, bindings are in an older style)
The good news is that the package has been added to `purescript/package-set`, so now it is possible to install it with `spago install phaser` (or purescript-phaser)
Now I have figure out how to update the versions in the registry, as the one available there is` v0.0.1` 😅

**Comment by hugh-fox** [comment]
No rush! I'm surprised, I just assumed it would be supported. Congratulations on an official package :)

**Review by lfarroco — CHANGES_REQUESTED** [review]
the code changes look good to me! the only thing that needs change is to move the `super-mario.png` file to a `assets` dir inside its example
by the way, I'm thinking about having a separated repo for the examples (where we can also include the compiled output)

**Comment by lfarroco** [comment]
@Rekihyt going to approve because I'm setting up some example pages and I'd like to include your example as well 🙂 
during the initial set up I can move the image file

**Pull request merged**
